## Imports

In [1]:
import numpy as np
import pandas as pd 

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [6]:
X =iris.data

In [7]:
y = iris.target

##### label encoding

In [9]:
from tensorflow.keras.utils import to_categorical

In [10]:
y = to_categorical(y)

In [13]:
# y

## Split the Data into Training and Test


In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.30,random_state=42)

In [17]:
X_train.shape

(105, 4)

In [18]:
X_test.shape

(45, 4)

In [19]:
y_train.shape

(105, 3)

In [20]:
y_test.shape

(45, 3)

## Standardizing the Data

Usually when using Neural Networks, you will get better performance when you standardize the data. Standardization just means normalizing the values to all fit between a certain range, like 0-1, or -1 to 1.

In [21]:
from sklearn.preprocessing import MinMaxScaler

In [22]:
scaler_object = MinMaxScaler()

In [23]:
scaled_X_train = scaler_object.fit_transform(X_train)
scaled_X_test = scaler_object.transform(X_test)

Ok, now we have the data scaled!

In [24]:
from tensorflow.keras import Sequential

In [25]:
from tensorflow.keras.layers import Dense

In [37]:
model = Sequential()
model.add(Dense(8,input_dim=4,activation ='relu'))
model.add(Dense(8,input_dim=4,activation ='relu'))
#output
model.add(Dense(3,activation ='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [38]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_12 (Dense)             (None, 8)                 40        
_________________________________________________________________
dense_13 (Dense)             (None, 8)                 72        
_________________________________________________________________
dense_14 (Dense)             (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [39]:
model.fit(scaled_X_train,y_train,epochs=150,verbose=2)

Epoch 1/150
4/4 - 0s - loss: 1.0264 - accuracy: 0.6476
Epoch 2/150
4/4 - 0s - loss: 1.0201 - accuracy: 0.6476
Epoch 3/150
4/4 - 0s - loss: 1.0146 - accuracy: 0.6476
Epoch 4/150
4/4 - 0s - loss: 1.0092 - accuracy: 0.6476
Epoch 5/150
4/4 - 0s - loss: 1.0038 - accuracy: 0.6476
Epoch 6/150
4/4 - 0s - loss: 0.9980 - accuracy: 0.6476
Epoch 7/150
4/4 - 0s - loss: 0.9927 - accuracy: 0.6476
Epoch 8/150
4/4 - 0s - loss: 0.9871 - accuracy: 0.6476
Epoch 9/150
4/4 - 0s - loss: 0.9814 - accuracy: 0.6476
Epoch 10/150
4/4 - 0s - loss: 0.9756 - accuracy: 0.6476
Epoch 11/150
4/4 - 0s - loss: 0.9696 - accuracy: 0.6476
Epoch 12/150
4/4 - 0s - loss: 0.9636 - accuracy: 0.6476
Epoch 13/150
4/4 - 0s - loss: 0.9572 - accuracy: 0.6476
Epoch 14/150
4/4 - 0s - loss: 0.9509 - accuracy: 0.6476
Epoch 15/150
4/4 - 0s - loss: 0.9444 - accuracy: 0.6476
Epoch 16/150
4/4 - 0s - loss: 0.9376 - accuracy: 0.6476
Epoch 17/150
4/4 - 0s - loss: 0.9302 - accuracy: 0.6476
Epoch 18/150
4/4 - 0s - loss: 0.9235 - accuracy: 0.6476
E

Epoch 147/150
4/4 - 0s - loss: 0.3578 - accuracy: 0.9524
Epoch 148/150
4/4 - 0s - loss: 0.3552 - accuracy: 0.9524
Epoch 149/150
4/4 - 0s - loss: 0.3520 - accuracy: 0.9619
Epoch 150/150
4/4 - 0s - loss: 0.3496 - accuracy: 0.9619


## Predicting New Unseen Data

In [40]:
scaled_X_test

array([[ 0.52941176,  0.36363636,  0.64285714,  0.45833333],
       [ 0.41176471,  0.81818182,  0.10714286,  0.08333333],
       [ 1.        ,  0.27272727,  1.03571429,  0.91666667],
       [ 0.5       ,  0.40909091,  0.60714286,  0.58333333],
       [ 0.73529412,  0.36363636,  0.66071429,  0.54166667],
       [ 0.32352941,  0.63636364,  0.07142857,  0.125     ],
       [ 0.38235294,  0.40909091,  0.44642857,  0.5       ],
       [ 0.76470588,  0.5       ,  0.71428571,  0.91666667],
       [ 0.55882353,  0.09090909,  0.60714286,  0.58333333],
       [ 0.44117647,  0.31818182,  0.5       ,  0.45833333],
       [ 0.64705882,  0.54545455,  0.71428571,  0.79166667],
       [ 0.14705882,  0.45454545,  0.05357143,  0.        ],
       [ 0.35294118,  0.68181818,  0.03571429,  0.04166667],
       [ 0.17647059,  0.5       ,  0.07142857,  0.        ],
       [ 0.23529412,  0.81818182,  0.07142857,  0.08333333],
       [ 0.58823529,  0.59090909,  0.64285714,  0.625     ],
       [ 0.64705882,  0.

In [41]:
# Spits out probabilities by default.
# model.predict(scaled_X_test)

In [42]:
model.predict_classes(scaled_X_test)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0], dtype=int64)

In [46]:
y_test

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [ ]:
# convert hot encodes to actual categories 

In [45]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0], dtype=int64)

# Evaluating Model Performance

In [49]:
from sklearn import metrics

In [50]:
model.metrics_names

['loss', 'accuracy']

In [51]:
model.evaluate(scaled_X_test,y_test)

2/2 [==============================] - 0s 1ms/step - loss: 0.2780 - accuracy: 0.9778


[0.2780008316040039, 0.9777777791023254]

In [55]:
predictions = model.predict_classes(scaled_X_test)

In [56]:
predictions

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0], dtype=int64)

In [57]:
y_test.argmax(axis =1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0], dtype=int64)

In [59]:
metrics.confusion_matrix(y_test.argmax(axis=1),predictions)

array([[19,  0,  0],
       [ 0, 12,  1],
       [ 0,  0, 13]], dtype=int64)

In [62]:
print(metrics.classification_report(y_test.argmax(axis=1),predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45



## Saving and Loading Models

In [64]:
from tensorflow.keras.models import load_model

In [65]:
model.save('iris_classification_model.h5')

In [66]:
newmodel = load_model('iris_classification_model.h5')

In [67]:
newmodel.predict_classes(X_test)

array([2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 0, 1, 0, 2, 2, 2, 2, 2, 1, 2,
       1, 2, 2, 2, 2, 2, 1, 1, 0, 0, 2, 1, 0, 2, 2, 1, 0, 0, 2, 2, 2, 0,
       0], dtype=int64)