In [10]:
def read_file(filepath):
    with open(filepath) as f:
        str_text = f.read()
    return str_text

In [ ]:
# read_file('moby_dick_four_chapters.txt')

In [5]:
import spacy

In [9]:
nlp = spacy.load('en_core_web_sm',disable=['parser', 'tagger','ner'])

In [11]:
nlp.max_length = 1198623

In [12]:
def separate_punc(doc_text):
    return [token.text.lower() for token in nlp(doc_text) if token.text not in '\n\n \n\n\n!"-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n '] 

In [13]:
d = read_file('moby_dick_four_chapters.txt')

In [15]:
tokens = separate_punc(d)

In [16]:
len(tokens)

11338

In [17]:
#25 words ----> network predict #26

In [18]:
train_len = 25+1
text_sequences = []

for i in range(train_len,len(tokens)):
    seq = tokens[i-train_len:i] #grabs 26 tokens (26-26 : 26)
    
    text_sequences.append(seq)
    
    

In [19]:
" ".join(text_sequences[0])

'call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on'

In [20]:
" ".join(text_sequences[1])

'me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore'

In [21]:
" ".join(text_sequences[2])

'ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore i'

In [22]:
len(text_sequences)

11312

## Keras Tokenizer

In [23]:
from keras_preprocessing.text import Tokenizer

In [24]:
tokenizer = Tokenizer()

In [25]:
tokenizer.fit_on_texts(text_sequences)

In [26]:
sequences = tokenizer.texts_to_sequences(text_sequences)

In [28]:
sequences[0]

[956,
 14,
 263,
 51,
 261,
 408,
 87,
 219,
 129,
 111,
 954,
 260,
 50,
 43,
 38,
 315,
 7,
 23,
 546,
 3,
 150,
 259,
 6,
 2712,
 14,
 24]

In [29]:
tokenizer.index_word

{1: 'the',
 2: 'a',
 3: 'and',
 4: 'of',
 5: 'i',
 6: 'to',
 7: 'in',
 8: 'it',
 9: 'that',
 10: 'he',
 11: 'his',
 12: 'was',
 13: 'but',
 14: 'me',
 15: 'with',
 16: 'as',
 17: 'at',
 18: 'this',
 19: 'you',
 20: 'is',
 21: 'all',
 22: 'for',
 23: 'my',
 24: 'on',
 25: 'be',
 26: "'s",
 27: 'not',
 28: 'from',
 29: 'there',
 30: 'one',
 31: 'up',
 32: 'what',
 33: 'him',
 34: 'so',
 35: 'bed',
 36: 'now',
 37: 'about',
 38: 'no',
 39: 'into',
 40: 'by',
 41: 'were',
 42: 'out',
 43: 'or',
 44: 'harpooneer',
 45: 'had',
 46: 'then',
 47: 'have',
 48: 'an',
 49: 'upon',
 50: 'little',
 51: 'some',
 52: 'old',
 53: 'like',
 54: 'if',
 55: 'they',
 56: 'would',
 57: 'do',
 58: 'over',
 59: 'landlord',
 60: 'thought',
 61: 'room',
 62: 'when',
 63: 'could',
 64: "n't",
 65: 'night',
 66: 'here',
 67: 'head',
 68: 'such',
 69: 'which',
 70: 'man',
 71: 'did',
 72: 'sea',
 73: 'time',
 74: 'other',
 75: 'very',
 76: 'go',
 77: 'these',
 78: 'more',
 79: 'though',
 80: 'first',
 81: 'sort',


In [32]:
for i in sequences[0]:
    print(f"{i} ---> {tokenizer.index_word[i]}")

956 ---> call
14 ---> me
263 ---> ishmael
51 ---> some
261 ---> years
408 ---> ago
87 ---> never
219 ---> mind
129 ---> how
111 ---> long
954 ---> precisely
260 ---> having
50 ---> little
43 ---> or
38 ---> no
315 ---> money
7 ---> in
23 ---> my
546 ---> purse
3 ---> and
150 ---> nothing
259 ---> particular
6 ---> to
2712 ---> interest
14 ---> me
24 ---> on


In [33]:
tokenizer.word_counts

OrderedDict([('call', 27),
             ('me', 2471),
             ('ishmael', 133),
             ('some', 758),
             ('years', 135),
             ('ago', 84),
             ('never', 449),
             ('mind', 164),
             ('how', 321),
             ('long', 374),
             ('precisely', 37),
             ('having', 142),
             ('little', 767),
             ('or', 950),
             ('no', 1003),
             ('money', 120),
             ('in', 5647),
             ('my', 1786),
             ('purse', 71),
             ('and', 9646),
             ('nothing', 281),
             ('particular', 152),
             ('to', 6497),
             ('interest', 24),
             ('on', 1716),
             ('shore', 26),
             ('i', 7150),
             ('thought', 676),
             ('would', 702),
             ('sail', 104),
             ('about', 1014),
             ('a', 10377),
             ('see', 416),
             ('the', 15540),
             ('watery', 26),
  

In [37]:
 vocab_size = len(tokenizer.word_index)

In [38]:
vocab_size

2717

### Convert to Numpy Matrix

In [39]:
import numpy as np

In [40]:
sequences = np.array(sequences)

### Train / Test Split

In [44]:
from tensorflow.keras.utils import to_categorical


In [45]:
sequences

array([[ 956,   14,  263, ..., 2712,   14,   24],
       [  14,  263,   51, ...,   14,   24,  957],
       [ 263,   51,  261, ...,   24,  957,    5],
       ...,
       [ 952,   12,  166, ...,  262,   53,    2],
       [  12,  166, 2711, ...,   53,    2, 2717],
       [ 166, 2711,    3, ...,    2, 2717,   26]])

In [46]:
# grabbing all the word except the lasty word 
X = sequences[:,:-1]

# grabbing the last word

y = sequences[:,-1]

In [47]:
y

array([  24,  957,    5, ...,    2, 2717,   26])

In [48]:
X

array([[ 956,   14,  263, ...,    6, 2712,   14],
       [  14,  263,   51, ..., 2712,   14,   24],
       [ 263,   51,  261, ...,   14,   24,  957],
       ...,
       [ 952,   12,  166, ...,   11,  262,   53],
       [  12,  166, 2711, ...,  262,   53,    2],
       [ 166, 2711,    3, ...,   53,    2, 2717]])

In [49]:
y = to_categorical(y,num_classes=vocab_size+1)

In [50]:
seq_len = X.shape[1]

In [52]:
X.shape

(11312, 25)

In [51]:
seq_len

25

## Creating an LSTM based model

In [55]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense , LSTM , Embedding

In [69]:
def create_model(vocabulary_size , seq_len):
    model = Sequential()
    model.add(Embedding(vocabulary_size,seq_len,input_length=seq_len))
    model.add(LSTM(seq_len*2,return_sequences =True))
    model.add(LSTM(50))
    model.add(Dense(50,activation='relu'))
    
    model.add(Dense(vocabulary_size,activation='softmax'))
    
    model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
    
    model.summary()
    
    print(f"vocabsize = {vocabulary_size} , seq_len = {seq_len}")
    return model

In [70]:
model = create_model(vocab_size + 1,seq_len)

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (None, 25, 25)            67950     
_________________________________________________________________
lstm_9 (LSTM)                (None, 25, 50)            15200     
_________________________________________________________________
lstm_10 (LSTM)               (None, 50)                20200     
_________________________________________________________________
dense_8 (Dense)              (None, 50)                2550      
_________________________________________________________________
dense_9 (Dense)              (None, 2718)              138618    
Total params: 244,518
Trainable params: 244,518
Non-trainable params: 0
_________________________________________________________________
vocabsize = 2718 , seq_len = 25


In [71]:
from pickle import dump,load

In [72]:
model.fit(X,y,batch_size=128,epochs=300,verbose=1)

Epoch 1/300
89/89 [==============================] - 1s 8ms/step - loss: 6.9764 - accuracy: 0.0466
Epoch 2/300
89/89 [==============================] - 1s 8ms/step - loss: 6.3769 - accuracy: 0.0529
Epoch 3/300
89/89 [==============================] - 1s 8ms/step - loss: 6.3462 - accuracy: 0.0529
Epoch 4/300
89/89 [==============================] - 1s 8ms/step - loss: 6.2984 - accuracy: 0.0529
Epoch 5/300
89/89 [==============================] - 1s 8ms/step - loss: 6.1831 - accuracy: 0.0529
Epoch 6/300
89/89 [==============================] - 1s 8ms/step - loss: 6.1104 - accuracy: 0.0529
Epoch 7/300
89/89 [==============================] - 1s 8ms/step - loss: 6.0437 - accuracy: 0.0529
Epoch 8/300
89/89 [==============================] - 1s 8ms/step - loss: 5.9625 - accuracy: 0.0566
Epoch 9/300
89/89 [==============================] - 1s 8ms/step - loss: 5.8975 - accuracy: 0.0644
Epoch 10/300
89/89 [==============================] - 1s 8ms/step - loss: 5.8373 - accuracy: 0.0671
Epoch 11/

89/89 [==============================] - 1s 8ms/step - loss: 3.5032 - accuracy: 0.2313
Epoch 84/300
89/89 [==============================] - 1s 8ms/step - loss: 3.4803 - accuracy: 0.2344
Epoch 85/300
89/89 [==============================] - 1s 8ms/step - loss: 3.4540 - accuracy: 0.2366
Epoch 86/300
89/89 [==============================] - 1s 8ms/step - loss: 3.4308 - accuracy: 0.2381
Epoch 87/300
89/89 [==============================] - 1s 8ms/step - loss: 3.4111 - accuracy: 0.2395
Epoch 88/300
89/89 [==============================] - 1s 8ms/step - loss: 3.3768 - accuracy: 0.2476
Epoch 89/300
89/89 [==============================] - 1s 8ms/step - loss: 3.3566 - accuracy: 0.2494
Epoch 90/300
89/89 [==============================] - 1s 8ms/step - loss: 3.3340 - accuracy: 0.2525
Epoch 91/300
89/89 [==============================] - 1s 8ms/step - loss: 3.3019 - accuracy: 0.2600
Epoch 92/300
89/89 [==============================] - 1s 8ms/step - loss: 3.2757 - accuracy: 0.2653
Epoch 93/300


89/89 [==============================] - 1s 8ms/step - loss: 2.0870 - accuracy: 0.4967
Epoch 165/300
89/89 [==============================] - 1s 8ms/step - loss: 2.0713 - accuracy: 0.4980
Epoch 166/300
89/89 [==============================] - 1s 8ms/step - loss: 2.0514 - accuracy: 0.5030
Epoch 167/300
89/89 [==============================] - 1s 8ms/step - loss: 2.0457 - accuracy: 0.5096
Epoch 168/300
89/89 [==============================] - 1s 8ms/step - loss: 2.0536 - accuracy: 0.5025
Epoch 169/300
89/89 [==============================] - 1s 8ms/step - loss: 2.0261 - accuracy: 0.5086
Epoch 170/300
89/89 [==============================] - 1s 8ms/step - loss: 2.0143 - accuracy: 0.5164
Epoch 171/300
89/89 [==============================] - 1s 8ms/step - loss: 1.9959 - accuracy: 0.5160
Epoch 172/300
89/89 [==============================] - 1s 8ms/step - loss: 1.9910 - accuracy: 0.5186
Epoch 173/300
89/89 [==============================] - 1s 8ms/step - loss: 1.9807 - accuracy: 0.5211
Epoc

89/89 [==============================] - 1s 8ms/step - loss: 1.3220 - accuracy: 0.6755
Epoch 246/300
89/89 [==============================] - 1s 8ms/step - loss: 1.3112 - accuracy: 0.6711
Epoch 247/300
89/89 [==============================] - 1s 8ms/step - loss: 1.3056 - accuracy: 0.6765
Epoch 248/300
89/89 [==============================] - 1s 8ms/step - loss: 1.2970 - accuracy: 0.6782
Epoch 249/300
89/89 [==============================] - 1s 8ms/step - loss: 1.2917 - accuracy: 0.6795
Epoch 250/300
89/89 [==============================] - 1s 8ms/step - loss: 1.2819 - accuracy: 0.6829
Epoch 251/300
89/89 [==============================] - 1s 8ms/step - loss: 1.2806 - accuracy: 0.6789
Epoch 252/300
89/89 [==============================] - 1s 8ms/step - loss: 1.2911 - accuracy: 0.6773
Epoch 253/300
89/89 [==============================] - 1s 8ms/step - loss: 1.2612 - accuracy: 0.6828
Epoch 254/300
89/89 [==============================] - 1s 8ms/step - loss: 1.2519 - accuracy: 0.6901
Epoc

In [73]:
# save the model to file
model.save('epochBIG.h5')
# save the tokenizer
dump(tokenizer, open('epochBIG', 'wb'))

# Generating New Text

In [74]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [98]:
def generate_text(model,tokenizer,seq_len,seed_text,num_gen_words):
    '''
    INPUTS:
    model : model that was trained on text data
    tokenizer : tokenizer that was fit on text data
    seq_len : length of training sequence
    seed_text : raw string text to serve as the seed
    num_gen_words : number of words to be generated by model
    '''
    # Final Output
    output_text=[]
    
    # Intial Seed Sequence
    input_text = seed_text
    
    # Create num_gen_words
    for i in range(num_gen_words):
        
        # Take the input text string and encode it to a sequence
        encoded_text = tokenizer.texts_to_sequences([input_text])[0]
        
        
#         print(f"encoded text : {tokenizer.texts_to_sequences([input_text])}")
        
        # Pad sequences to our trained rate (50 words in the video)
        pad_encoded = pad_sequences([encoded_text],maxlen=seq_len,truncating='pre')
        
        # Predict Class Probabilities for each word
        pred_word_ind = model.predict_classes(pad_encoded,verbose =0)[0]
        
        
#         print(model.predict_classes(pad_encoded,verbose =0))
        
        # Grab word
        pred_word = tokenizer.index_word[pred_word_ind]
        
        # Update the sequence of input text (shifting one over with the new word)
        input_text= " " + pred_word
        
        output_text.append(pred_word)
    
    # Make it look like a sentence.
    return " ".join(output_text)

### Grab a random seed sequence

In [78]:
text_sequences[0]

['call',
 'me',
 'ishmael',
 'some',
 'years',
 'ago',
 'never',
 'mind',
 'how',
 'long',
 'precisely',
 'having',
 'little',
 'or',
 'no',
 'money',
 'in',
 'my',
 'purse',
 'and',
 'nothing',
 'particular',
 'to',
 'interest',
 'me',
 'on']

In [79]:
import random
random.seed(101)
random_pic = random.randint(0,len(text_sequences))

In [80]:
random_seed_text = text_sequences[random_pic]

In [85]:
random_seed_text

['thought',
 'i',
 'to',
 'myself',
 'the',
 'man',
 "'s",
 'a',
 'human',
 'being',
 'just',
 'as',
 'i',
 'am',
 'he',
 'has',
 'just',
 'as',
 'much',
 'reason',
 'to',
 'fear',
 'me',
 'as',
 'i',
 'have']

In [87]:
seed_text = ' '.join(random_seed_text)

In [99]:
generate_text(model,tokenizer,seq_len,seed_text,num_gen_words=25)

'do he was a whalin instinct was a whalin instinct was a whalin instinct was a whalin instinct was a whalin instinct was a whalin'